=== ScottLogic/Technology-Carbon-Standard/schemas/tech_carbon_standard/v0.0.2.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://techcarbonstandard.org/schemas/tech_carbon_standard/v0.0.2.json",
  "title": "Technology Carbon Standard",
  "description": "The Technology Carbon Standard is a standard for measuring and managing the carbon emissions of technology products and services.",
  "type": "object",
  "$defs": {
    "emissions_def": {
      "type": "object",
      "properties": {
        "emissions": {
          "type": "number",
          "description": "Total carbon emissions in kgCO2e",
          "minimum": 0
        },
        "notes": {
          "type": "string",
          "description": "Notes on the carbon emissions"
        }
      },
      "required": ["emissions"],
      "additionalProperties": false
    },
    "scope_2_emissions_def": {
      "type": "object",
      "properties": {
        "emissions": {
          "type": "number",
          "description": "Total carbon emissions in kgCO2e",
          "minimum": 0
        },
        "notes": {
          "type": "string",
          "description": "Notes on the carbon emissions"
        },
        "method": {
          "enum": ["location-based", "market-based", "mixed-methods", "other"],
          "description": "Provide the method used for calculating the emissions. Must be one of: 'location-based', 'market-based', 'mixed-methods', or 'other."
        }
      },
      "required": ["emissions"],
      "additionalProperties": false
    }
  },
  "properties": {
    "schema_version": {
      "type": "string",
      "description": "Version of the Tech Carbon Standard schema used for this report.",
      "enum": ["0.0.1"]
    },
    "upstream_emissions": {
      "type": "object",
      "description": "Upstream emissions relating to the embodied carbon of hardware and the development of software.",
      "properties": {
        "software": {
          "$ref": "#/$defs/emissions_def",
          "description": "Emissions associated with developing and delivering off-the-shelf and open-source software installed on the organisation's systems."
        },
        "employee_hardware": {
          "$ref": "#/$defs/emissions_def",
          "description": "Embodied carbon emissions associated with hardware devices owned by an organisation, including emissions from the manufacture, transportation, installation, maintenance, and end-of-life of a device."
        },
        "network_hardware": {
          "$ref": "#/$defs/emissions_def",
          "description": "When considering the upstream emissions of a network, consider the embodied carbon of any networking devices that are owned by the organisation."
        },
        "server_hardware": {
          "$ref": "#/$defs/emissions_def",
          "description": "Servers, storage systems, and data centre infrastructure installed on-premise."
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "direct_emissions": {
      "type": "object",
      "description": "Direct running costs that are attributed to the electricity powering servers, networks and devices.",
      "properties": {
        "onsite_employee_hardware": {
          "$ref": "#/$defs/scope_2_emissions_def",
          "description": "Emissions associated with the operation and use of devices owned by an organisation."
        },
        "networking": {
          "$ref": "#/$defs/scope_2_emissions_def",
          "description": "Emissions associated with the operation and use of networking and infrastructure."
        },
        "servers": {
          "$ref": "#/$defs/scope_2_emissions_def",
          "description": "The energy consumed by on-premise servers and data centres."
        },
        "generators": {
          "$ref": "#/$defs/emissions_def",
          "description": "Any fossil fuel-powered generators, solar PV, wind turbines, or other systems installed on-site to supply electricity to technology equipment."
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "indirect_emissions": {
      "type": "object",
      "description": "Indirect running carbon costs that are attributed to external hardware and service solutions.",
      "properties": {
        "offsite_employee_hardware": {
          "$ref": "#/$defs/emissions_def",
          "description": "The emissions incurred by computers (desktops, laptops), monitors, printers, and other devices used by employees, when used out-of-office."
        },
        "cloud_services": {
          "$ref": "#/$defs/emissions_def",
          "description": "The emissions associated with cloud platform services like compute, storage, and networking."
        },
        "saas": {
          "$ref": "#/$defs/emissions_def",
          "description": "The emissions associated with Software-as-a-Service (SaaS) applications."
        },
        "managed_services": {
          "$ref": "#/$defs/emissions_def",
          "description": "The associated emissions of Managed Security Operations, IT support and data backup services."
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "downstream_emissions": {
      "type": "object",
      "description": "Carbon associated with the use of products and services produced by the organisation.",
      "properties": {
        "end_user_devices": {
          "$ref": "#/$defs/emissions_def",
          "description": "This considers the emissions generated from the electricity consumption of devices such as desktops, laptops, tablets, and mobile phones that utilise the products or services provided by an organisation."
        },
        "network_data_transfer": {
          "$ref": "#/$defs/emissions_def",
          "description": "These emissions are associated with the infrastructure enabling data transmission, enabling end-users to access the products and services."
        },
        "downstream_infrastructure": {
          "$ref": "#/$defs/emissions_def",
          "description": "These emissions encompass the physical infrastructure and systems that end-users deploy or operate as a direct result of using an organisation's products or services, including IoT devices, locally hosted servers, storage systems, and specialised hardware installations."
        }
      },
      "required": [],
      "additionalProperties": false
    }
  },
  "required": [
    "schema_version"
  ],
  "additionalProperties": false
}

=== ScottLogic/Technology-Carbon-Standard/schemas/examples/tech_carbon_standard/v0.0.1.json
{
    "schema_version": "0.0.1",
    "upstream_emissions": {
        "software": {
            "emissions": 0,
            "notes": "Not currently meaningfully calculable or estimatable"
        },
        "employee_hardware": {
            "emissions": 55000,
            "notes": "Embodied carbon of purchased laptops and monitors, using production and transportation figures from manufacturers' product lifecycle reports"
        },
        "network_hardware": {
            "emissions": 1000,
            "notes": "Loose estimate, based on minimal hardware purchase"
        },
        "server_hardware": {
            "emissions": 0,
            "notes": "No servers or storage hardware purchased"
        }
    },
    "direct_emissions": {
        "onsite_employee_hardware": {
            "emissions": 5000,
            "notes": "Calculated using UK grid carbon intensity 2023; exact laptop and monitor counts; and, average laptop and monitor power consumption figures"
        },
        "networking": {
            "emissions": 1000,
            "notes": "Loose estimate, based on known minimal networking infrastructure"
        },
        "servers": {
            "emissions": 1000,
            "notes": "Loose estimate, based on known minimal infrastructure"
        },
        "generators": {
            "emissions": 0,
            "notes": "No generators"
        }
    },
    "indirect_emissions": {
        "offsite_employee_hardware": {
            "emissions": 3000,
            "notes": "Calculated using UK grid carbon intensity 2023; exact laptop and monitor counts; and, average laptop and monitor power consumption figures"
        },
        "cloud_services": {
            "emissions": 5000,
            "notes": "Full cloud estate measured using Cloud Carbon Footprinting tool"
        },
        "saas": {
            "emissions": 84000,
            "notes": "Spend-based estimate calculated using Plan A platform"
        },
        "managed_services": {
            "emissions": 1000,
            "notes": "Loose estimate, based on known minimal managed services"
        }
    }
}
